///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/*
 * 
 * Purpose: The logic for loading animation circle
 * Authors: Tom, Collin, Hugo and Sharukh
 * Date: 14/08/2018
 * Reviewers: Sharukh, Gang and May
 * Review date: 10/09/2018
 * 
 * /
 ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  */



using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class circleRotator : MonoBehaviour
{

    RectTransform rectComponent;
    //Adjust rotating speed here
    readonly float rotateSpeed = 400f;

    // Intialization for gameobject
    void Start()
    {
        rectComponent = GetComponent<RectTransform>();
    }

    // Logic to rotate circle over time
    void Update()
    {
        rectComponent.Rotate(0f, 0f, rotateSpeed * Time.deltaTime);
    }
}